### ISSUE TITLE
遊戲室架構用哪一種????

### ISSUE THREAD

**Issue by 57hex** [ShiriNmi1520/OSTB#1]
統一一下用 Firebase 或是用 socket 內建的吧？
都沒統一的話豆頁痛，再跟我說一下，感謝。

**Comment by ShiriNmi1520** [comment]
socket.join只是讓player待在一個room底下
發訊息或其他資料時只需要往room丟就好(不須分event事件)
Firebase上儲存的是房間裡每位玩家的status
